### ISSUE TITLE
Could not decode a text frame as UTF-8

### ISSUE THREAD

**Issue by SolarisYan** [jupyter-incubator/nb2kg#26]
Hi there, i use nb2kg with enterprise-gateway in k8s, and jupyterhub with jupyterlab 
widgets [itk-jupyter-widgets,](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets) when i run the code 

image = itk.imread(file_name)
view(image)

it will have error like below(infact is the code `view(image)`):
WebSocket connection to 'wss://xxx.com/user/admin/api/kernels/33f732c2-9e84-4f3f-8ec5-827ebd793212/channels?session_id=af3a9dda-9ac6-47cf-a142-73087cde1ee2&token=bcc21fd62e2a4dba83d7e3f20d04d927' failed: Could not decode a text frame as UTF-8.
then it will disconnect the kernel connection , and reconnecting in 1 seconds.
I have test it without gateway,say use local kernel within jupyterlab, all will be ok.

**Comment by SolarisYan** [comment]
solved, close

**Comment by kevin-bates** [comment]
@SolarisYan - could you please indicate what you did to solve this in case its encountered by others?

**Comment by SolarisYan** [comment]
@kevin-bates Sorry for the late reply, i will push the code back with a PR in a moment
