### ISSUE TITLE
whitelisting of kernels

### ISSUE THREAD

**Issue by Gsbreddy** [jupyter-incubator/nb2kg#27]
I am using nb2kg with EG and in the kernelspecs I can see both python3 and spark-python-yarn-mode. But When I dont want to see python3 kernel. I found that in notebook conf a similar config exists as follows 
`#Removing default python kernel`
`c.KernelSpecManager.ensure_native_kernel = False`
`c.KernelSpecManager.whitelist = {'spark_python_yarn_cluster'} `

But this isnt working with nb2kg since its overriding the kernelspecmanager. Any ideas on this?

**Comment by kevin-bates** [comment]
When nb2kg is configured kernel management (and kernelspecs) are performed (and derived) from the gateway (EG) server.  As a result, this should be configured in the gateway configuration.

**Comment by Gsbreddy** [comment]
Is there some config in EG? I couldn’t find any in the docs.

**Comment by kevin-bates** [comment]
EG is usually [started from a script](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/enterprise-gateway/start-enterprise-gateway.sh) since its more like a service, but it can also be configured like the other jupyter applications.
```bash
[elyra@elyra-omg-node-1 ~]$ jupyter enterprisegateway --generate-config
Overwrite /home/elyra/.jupyter/jupyter_enterprise_gateway_config.py with default config? [y/N]y
Writing default config to: /home/elyra/.jupyter/jupyter_enterprise_gateway_config.py
```

**Comment by Gsbreddy** [comment]
Sorry I’ll rephrase my question. Is there any configuration like EG_KERNEL_WHITELIST to show only required kernels. Let’s say I have 6 types of kernels but I want to whitelist only 3 kernels.

**Comment by Gsbreddy** [comment]
But in case of Bare metal machines it has no env called EG_KERNEL_WHITELIST.

**Comment by kevin-bates** [comment]
True.  We use the env to convey _into_ the container.  However, the [actual configurable item](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/enterprise-gateway/start-enterprise-gateway.sh#L28) is the same as Notebook since it's all inherited.

**Comment by Gsbreddy** [comment]
Ok let me try this out. Thanks 🙂

**Comment by Gsbreddy** [comment]
It's working thanks.
