### ISSUE TITLE
Need information on restart of NB2KG Server

### ISSUE THREAD

**Issue by aniket02k** [jupyter-incubator/nb2kg#48]
Hi,
I wanted to restart NB2KG server . Is there any API available to restart the nb2kg server?

**Comment by kevin-bates** [comment]
Not explicitly.  NB2KG is a server extension, so its lifecycle is that of the notebook server.  As a result, "restart" equates to stopping and starting the notebook server.

**Comment by aniket02k** [comment]
> Not explicitly.  NB2KG is a server extension, so its lifecycle is that of the notebook server.  As a result, "restart" equates to stopping and starting the notebook server.

Thank you kevin!
